### PR TITLE
add NR's init file

### PR DESCRIPTION
**Pull request by nistara**
Need to clean up and streamline the init file, but here it is for the moment.

### CODE REVIEW

**Comment by MilesMcBain** [comment]
Oh no I really thought I had merged this sorry. Thanks for the contribution.

**Comment by MilesMcBain** [comment]
@nistara would you be comfortable with me adding this now? I can still see the proposed change.

**Comment by nistara** [comment]
@MilesMcBain Please go ahead. I thought you might not want to add more contributors so I closed the pull request. Thanks for following up!

**Comment by MilesMcBain** [comment]
Done! Thankyou 👍

**Pull request closed without merging**
